backend/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

root 'worlds#home'

#resources makes the
#index, new, create, show, edit, 
#update, and destroy routes/actions
resources :worlds do
  resources :plots
  resources :characters 
end 

resources :plots
resources :characters 

#view world with most plots 
get 'worlds/most-plots' => 'worlds#show'

end

backend/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

backend/app/models/character.rb
class Character < ApplicationRecord
    belongs_to :world

    validates :name, presence: true
end

backend/app/models/plot.rb
class Plot < ApplicationRecord

    belongs_to :world

    validates :title, presence: true
end

backend/app/models/user.rb
class User < ApplicationRecord
 
  has_many :worlds
  #accepts_nested_attributes_for :worlds

  has_many :characters, through: :worlds
  has_many :plots, through: :worlds

  validates :email, uniqueness: true
 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable

         def self.from_omniauth(auth)  
          where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
            user.provider = auth.provider
            user.uid = auth.uid
            user.email = auth.info.email
            user.password = Devise.friendly_token[0,20]
          end
        end
end

backend/app/models/world.rb
class World < ApplicationRecord
    belongs_to :user

    has_many :characters, :dependent => :destroy
    accepts_nested_attributes_for :characters

    has_many :plots, :dependent => :destroy
    accepts_nested_attributes_for :plots

    validates :name, presence: true, uniqueness: true


    def self.search(search)
        if search
            world = World.find_by(name: search)
            if world 
                self.where(world_id: world)
        else
            @worlds = World.all
        end 
    else 
        @worlds = World.all 
        end
    end 

#most plots in a world
def self.most_plots
   joins(:plots).group("worlds.id").order("COUNT(*) DESC").select("worlds.*").limit(1)
end



end 

backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base 
  
end

backend/app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
    def github
        @user = User.from_omniauth(request.env["omniauth.auth"])
        sign_in_and_redirect @user
      end
end

backend/app/controllers/characters_controller.rb
class CharactersController < ApplicationController

    before_action :authenticate_user!
    before_action :set_world
    before_action :set_character, only: [:show, :edit, :update, :destroy]
   
    def index
        redirect_to worlds_path(@worlds)
    end

    def new
        @character = @world.characters.build
    end

    def show
    end

    def create
        @character = Character.new(character_params)
        @character.user_id = current_user.id

        if @character.save
            redirect_to world_character_path(@character.world, @character)
          else 
            render 'new'
          end 
    end
  

    def edit
    end

    def update
       

        if @character.update(character_params)
            redirect_to world_character_path(@character.world, @character)
          else 
            render 'edit'
          end 
    
    end

    def destroy
        @character.destroy
        
        redirect_to world_path(@character.world)
    end

    private 

    def character_params
        params.require(:character).permit(
            :name,
            :type,
            :species,
            :description,
            :user_id,
            :world_id
        )
    end

   
    def set_world
        @world = World.find_by(id:params[:world_id])
    end

    def set_character
        @character = Character.find(params[:id])
    end 

end

backend/app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render(:status => 404)
  end

  def internal_server_error
    render(:status => 500)
  end
end

backend/app/controllers/plots_controller.rb
class PlotsController < ApplicationController

    before_action :authenticate_user!
    before_action :set_world

    def index
        redirect_to worlds_path(@worlds)
    end

    def new
        @plot = @world.plots.build
    end
    
    def show
        @plot = Plot.find(params[:id])
    end

    def create
        @plot = Plot.new(plot_params)
        
        if @plot.save
            redirect_to world_plot_path(@plot.world, @plot)
          else 
            render 'new'
          end 
        end

    def edit
       @plot = Plot.find(params[:id])
    end

    def update
        @plot = Plot.find(params[:id])

        if @plot.update(plot_params)
            redirect_to world_plot_path(@plot.world, @plot)
        
        else
           render 'edit'
        end
    end

    def destroy
        @plot = Plot.find(params[:id])
        @plot.destroy

        redirect_to world_path(@plot.world)
    end

    private 

    def plot_params
        params.require(:plot).permit(
            :title,
            :description,
            :user_id,
            :world_id
        )
    end

    def set_world
        @world = World.find_by(id:params[:world_id])
    end

end

backend/app/controllers/worlds_controller.rb
class WorldsController < ApplicationController

    def index
        if params[:name]
             @worlds = World.where('name LIKE ?', "%#{params[:name]}%")
        else 
            @worlds = World.all 
        end 
            
    end

   def new
     @world = World.new
   end

    def home 
    end 

   def show
    if params[:id] == "most-plots"
        @world = World.most_plots.first

    else  
        @world = World.find(params[:id])

    end
    @characters = @world.characters
    @plots = @world.plots
   end 

# the create action saves info to 
#the database, while new 
#just makes a new instance 

def create
    @world = current_user.worlds.build(world_params)

    if @world.save
        redirect_to world_path(@world)
    else
       render 'new'
    end 
end 

def edit 
    @world = World.find(params[:id])
end 

def update
    @world = World.find(params[:id])

    if @world.update(world_params)
        redirect_to world_path(@world)
    else
       render 'edit'
    end 
end

def destroy
    @world = World.find(params[:id])
      @world.destroy

      redirect_to worlds_path
end 



private 

def world_params
    params.require(:world).permit(
        :name,
        :description,
        :user_id, 
        :search
    )
end


end

backend/app/helpers/application_helper.rb
module ApplicationHelper

    #helper methods are used
    #within the views
end

backend/app/helpers/callbacks_helper.rb
module CallbacksHelper
end

backend/app/helpers/characters_helper.rb
module CharactersHelper
end

backend/app/helpers/errors_helper.rb
module ErrorsHelper
end

backend/app/helpers/plots_helper.rb
module PlotsHelper
end

backend/app/helpers/worlds_helper.rb
module WorldsHelper
end

backend/app/views/characters/_form.html.erb
<%= form_for(@character) do |f| %>

    <% if @character.world.nil? %>
        <label class="label">character world:</label>
        <%= f.select :world_id, options_from_collection_for_select(world.all, :id, :name) %><br>
        <i>Don't see your world? Create a new world <%= link_to "here.", new_world_path %></i><br><br>
    <% else %>
        <%= hidden_field_tag "character[world_id]", @character.world_id %>
    <% end %>

    <label class="label"> Name: </label>
    <%= f.text_field :name %><br><br>

    <label class="label">Character Class:</label>
    <%= f.text_field :type %><br><br>

    <label class="label">Species:</label>
    <%= f.text_field :species %><br><br>

    <label class="label">Description:</label>
    <%= f.text_field :description %><br><br>
    
    <%= f.hidden_field :user_id, value:current_user.id %>
 
   <input type="submit" value="Submit" class="button is-primary">
<% end %>

backend/app/views/characters/edit.html.erb
<h1>Edit a Character!</h1>

<%= render partial: "form", locals: {character: @character} %>

<% @character.errors.full_messages.each do |error| %>
<%= error %> <br>
<% end %>

backend/app/views/characters/index.html.erb
<h1> char index page</h1>

<ul>
    <% @characters.each do |c| %>
       <li><%= link_to c.name, world_character_path(c.world, c) %></li>   
    <br>
    <% end %>
</ul>
<br>
<%= link_to 'create a new character', characters_new_path %>

backend/app/views/characters/new.html.erb
<h1>Create a character!</h1>

<%= render partial: "form", locals: {character: @character} %>

<% @character.errors.full_messages.each do |error| %>
<%= error %> <br>
<% end %>

backend/app/views/characters/show.html.erb
<% if @character.user_id == current_user.id %>
    <%= link_to "Edit character", edit_world_character_path(@world) %> <br>
    
    <%= link_to "delete character", @character, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% else %>
  This character belongs to <%= @world.user.email %>
  
<% end %>

<p>
  <strong>Name:</strong>
  <%= @character.name  %>
</p>
 
<p>
  <strong>Type:</strong>
  <%= @character.type %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @character.description %>
</p>

<p>
  <strong>character species:</strong>
  <%= @character.species %>
</p>

<br>
<h2>
<%= link_to 'BACK', world_path(@world) %>

</h2>

backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Worldy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="/">Worlding</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/worlds">All Worlds</a>
        </li>

      <li class="nav-item">
  <a class="nav-link" href="/">Home</a>
</li>

      </ul>


<p class="navbar-text">
<br>
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>

    </div>
  </div>
</nav>
<br>
<br>

    <div class="container">

    <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

      <%= yield %>
    </div>  

<a href="http://localhost:3000/">
<footer>
  <div class="container">
    
   <svg width="2.5em" height="3em" viewBox="0 0 16 16" class="bi bi-info-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
  <path d="M8.93 6.588l-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588z"/>
  <circle cx="8" cy="4.5" r="1"/>
</svg>
</a>

<a href="http://localhost:3000/users/edit">
<svg width="3.5em" height="3em" viewBox="0 0 16 16" class="bi bi-file-person" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M4 1h8a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2zm0 1a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1H4z"/>
  <path d="M13.784 14c-.497-1.27-1.988-3-5.784-3s-5.287 1.73-5.784 3h11.568z"/>
  <path fill-rule="evenodd" d="M8 10a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
</svg>
</a>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

<a href="https://github.com/wonderfulkasey/worldy">
<svg width="2.5em" height="3em" viewBox="0 0 16 16" class="bi bi-code-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
  <path fill-rule="evenodd" d="M6.854 4.646a.5.5 0 0 1 0 .708L4.207 8l2.647 2.646a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 0 1 .708 0zm2.292 0a.5.5 0 0 0 0 .708L11.793 8l-2.647 2.646a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708 0z"/>
</svg>
</a>


<br>
<br>
<br>



Worlding <%= Time.now.year %>
    <br>
    <br>

     Today's date is : 
        <strong>
         <span id="datetime"></span>
         <script>
var dt = new Date();
document.getElementById("datetime").innerHTML = dt.toLocaleString();
</script>
        </strong>  

  </div>
<br>
<br>
</footer>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

  </body>
</html>

backend/app/views/plots/_form.html.erb
<%= form_for(@plot) do |f| %>

    <% if @plot.world.nil? %>
        <label class="label">plot world:</label>
        <%= f.select :world_id, options_from_collection_for_select(world.all, :id, :name) %><br>
        <i>Don't see your world? Create a new world <%= link_to "here.", new_world_path %></i><br><br>
    <% else %>
        <%= hidden_field_tag "plot[world_id]", @plot.world_id %>
    <% end %>

    <label class="label"> title: </label>
    <%= f.text_field :title %><br><br>

    <label class="label">Description:</label>
    <%= f.text_field :description %><br><br>
    
    <%= f.hidden_field :user_id, value:current_user.id %>
 
   <input type="submit" value="Submit" class="button is-primary">
<% end %>

backend/app/views/plots/edit.html.erb
<h1>Edit a plot!</h1>

<%= render partial: "form", locals: {plot: @plot} %>

backend/app/views/plots/index.html.erb
<h1>plot index page</h1>

<ul>
    <% @plots.each do |p| %>
       <li><%= link_to p.title, world_plot_path(p.world, p) %></li>
    <% end %> 
</ul>

<%= link_to 'create a new plot', plots_new_path %>

backend/app/views/plots/new.html.erb
<h1>Create a plot!</h1>

<%= render partial: "form", locals: {plot: @plot} %>

<% @plot.errors.full_messages.each do |error| %>
<%= error %> <br>
<% end %>

backend/app/views/plots/show.html.erb
<% if @plot.user_id == current_user.id %>
    <%= link_to "Edit plot", edit_world_plot_path(@world) %> <br>
   
   <%= link_to "delete plot", @plot, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% else %>
  This character belongs to <%= @world.user.email %>
  
<% end %>

<p>
  <strong>Title:</strong>
  <%= @plot.title  %>
</p>

<p>
  <strong>Description:</strong>
  <%= @plot.description %>
</p>
<br>
<h2>
<%= link_to 'BACK', world_path(@world) %>

</h2>

backend/app/views/worlds/_form.html.erb
<%= form_for(world) do |f| %>
    <label class="label">world name:</label>
    <%= f.text_field :name %><br><br>

    <label class="label">description:</label>
    <%= f.text_field :description %><br><br>

    <input type="submit" value="Submit" class="button is-primary">
<% end %>

backend/app/views/worlds/edit.html.erb
<h1>Edit world!</h1>

<%= render partial: "form", locals: {world: @world} %>

<% @world.errors.full_messages.each do |error| %>
<%= error %> <br>
<% end %>

backend/app/views/worlds/home.html.erb
<h1>Welcome to Worlding!</h1>
<p>Here you can share your world and character ideas, 
as well as read up on others.</p>
<br>
<br>
    <h3>Want the world with the most plots?</h3>

    <%= link_to "Click here", worlds_most_plots_path %> to view the world with the most plots.
    
<br>

backend/app/views/worlds/index.html.erb
<h1> world index page </h1>

<div>
    <strong><%= link_to "CREATE A NEW WORLD", new_world_path %></strong>
    </div>
    <br>

    <br>

    <h2>Search by World:</h2>
    <%= form_tag worlds_path, :method => "get" do %>
        <%= text_field_tag :name, params[:name] %>
        <%= submit_tag("Search", :name => nil) %>
    <% end %>

    <br>

<ul>
<% @worlds.each do |w| %>

    <li><%= link_to w.name, world_path(w) %> 
   </li>
   <br> 
   
<% end %>
</ul>
<br>

backend/app/views/worlds/new.html.erb
<h1>Create a World!</h1>

<%= render partial: "form", locals: {world: @world} %>

<% @world.errors.full_messages.each do |error| %>
<%= error %> <br>
<% end %>

<%= link_to 'Back', worlds_path %>

backend/app/views/worlds/show.html.erb
<% if @world.user_id == current_user.id %>
<br>
    <%= link_to "EDIT WORLD", edit_world_path(@world) %> <br>
    <br>
    <%= link_to "delete world", @world, method: :delete, data: { confirm: 'Are you sure?' } %>
    <br>
    <br>
    <%= link_to "NEW CHARACTER", new_world_character_path(@world) %> <br>
    <%= link_to "NEW PLOT", new_world_plot_path(@world) %>
<br>
<br>

<% else %>
 <h3>Created by: <%= @world.user.email %>
 </h3>
<br>
<br>
<% end %>

<br>

<p>
  <strong>Name:</strong>
  <%= @world.name %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @world.description %>
</p>


<p>
  <h3>plots in <%= @world.name %> </h3>
            <% @plots.each do |p| %>
                
           <li><%= link_to p.title, world_plot_path(p.world, p) %></li>
 

            <% end %>
            <br>
</p>

<br>
<p>
            <h3>characters in <%= @world.name %></h3>
            <div>
             <% @characters.each do |c| %>
                
                  <li><%= link_to c.name, world_character_path(c.world, c) %></li>
 <% end %>
             </div>
</p>
<br>

<h2>
<%= link_to 'BACK', worlds_path %>

</h2>